### PR TITLE
Mods, commented

### PR DESCRIPTION
**Pull request by tommyw**
Hope this works for you!

### CODE REVIEW

**Comment by dubroe** [comment]
Hey sorry to be picky :)

Could you please put the code back to the original formatting so that when I view the diff I can see just the changes that you made?

I can do this myself but then you wouldn't get credit for me pulling in your pull request.

**Comment by tommyw** [comment]
I don't really know what you mean - I'm quite new to Git push/pull
requests. I just copied my code in (I also tried forking, but I guess
that's different)

No credit required. Just use it if it helps.

Finishing working now, can look tomorrow if need be.

On 28 June 2012 17:40, Elan Dubrofsky <
reply@reply.github.com

**Comment by dubroe** [comment]
Ok in that case I'll take care of it. Thanks very much for the contribution!

For future reference, what I was referring to is that when github shows me your pull request, I can look at a diff between my and your version to see what has changed. You can see it too. For your pull request, it's showing every line as changed, since you changed the number of tabs or something. So it's not very helpful in pinpointing what you did.

The easiest way to go through this process for me is to:
a) Fork the project
b) Download the code from the forked project (using git clone)
c) Make changes
d) Push your changes to the forked version
e) Click on "submit pull request" from your forked version on GitHub.

**Comment by dubroe** [comment]
Pull in your changes manually, after cleaning up formatting so the diff is more clear. Thanks so much!

**Comment by tommyw** [comment]
Thanks very much for the info Elan. It could be that the tabs messed up as
I'm using Windows?? Anyway, I'll bear this in mind.

Handy plugin, sure I'll use it a lot!

Cheers

Tom

On 28 June 2012 17:52, Elan Dubrofsky <
reply@reply.github.com

**Pull request closed without merging**
